config/routes.rb
Spree::Core::Engine.routes.draw do
  namespace :admin do
    resources :products do
      resources :docs do 
         collection do 
         	post :update_positions
      end
      	
      end
    end
  end
end

Rails.application.routes.draw do
  
end

app/models/spree/doc.rb
module Spree
  class Doc < Asset
    validate :no_attachment_errors

    # attr_accessible :alt, :attachment, :position, :viewable_type, :viewable_id

    has_attached_file :attachment,
      storage: :s3,
      s3_credentials: Proc.new{|a| a.instance.s3_credentials}

    before_post_process :skip_thumbnail_creation

    ALLOWED_CONTENT_TYPES = [ "application/msword","application/vnd.ms-excel","application/pdf" ]
    ALLOWED_FILE_EXTENSIONS = [ "pdf", "doc", "docx", "xls", "xlsx" ]

    def no_attachment_errors
      unless attachment.errors.empty?
        # uncomment this to get rid of the less-than-useful interrim messages
        # errors.clear
        errors.add :attachment, "Paperclip returned errors for file '#{attachment_file_name}' - check document source file."
        false
      end
    end

    def s3_credentials
      {
        bucket: ENV["S3_BUCKET"],
        access_key_id: ENV["S3_ACCESS_KEY"],
        secret_access_key: ENV["S3_SECRET"]
      }
    end
    private
    def skip_thumbnail_creation
      return false if (attachment_content_type =~ /application\/.*pdf/ or ALLOWED_CONTENT_TYPES.include?(attachment_content_type))
    end

  end
end

app/models/spree/product_decorator.rb
# Add "Document" to Product Model
Spree::Product.class_eval do
  delegate :docs, :to => :master, :prefix => true
  has_many :variant_docs, :source => :docs, :through => :variants_including_master, :order => :position
  alias_method :docs, :master_docs
end

app/models/spree/variant_decorator.rb
Spree::Variant.class_eval do
  has_many :docs, :as => :viewable, :order => :position, :dependent => :destroy
end

app/controllers/spree/admin/docs_controller.rb
module Spree
  module Admin
    class DocsController < ResourceController
      before_filter :load_data

      create.before :set_viewable
      update.before :set_viewable
      destroy.before :destroy_before

      private

        def location_after_save
          admin_product_docs_url(@product)
        end

        def load_data
          @product = Product.where(:permalink => params[:product_id]).first
          @variants = @product.variants.collect do |variant|
            [variant.options_text, variant.id]
          end
          @variants.insert(0, [Spree.t(:all), @product.master.id])
        end

        def set_viewable
          @doc.viewable_type = 'Spree::Variant'
          @doc.viewable_id = params[:doc][:viewable_id]
        end

        def destroy_before
          @viewable = @doc.viewable
        end

    end
  end
end

app/controllers/spree/admin/products_controller_decorator.rb
# Make the Doc Helper available to all views
Spree::Admin::ProductsController.class_eval do
    helper Spree::Admin::DocsHelper
end

app/controllers/spree/products_controller_decorator.rb
# Make the Doc Helper available to all views
Spree::ProductsController.class_eval do
    helper Spree::DocsHelper
end

app/helpers/spree/admin/docs_helper.rb
module Spree
  module Admin
      module DocsHelper
  def get_doc_icon(doc)
    word_icon = 'word_icon.png'
    excel_icon = 'excel_icon.png'
    pdf_icon = 'pdf_icon.png'
    file_extension = doc.attachment.url.split(".")[-1].downcase
    if file_extension.include?('pdf')
      return pdf_icon
    elsif file_extension.include?('docx')
      return word_icon
    else
      return excel_icon
    end
  end
end
end
end


app/helpers/spree/docs_helper.rb
module Spree
module DocsHelper
  def get_doc_icon(doc)
    word_icon = 'word_icon.png'
    excel_icon = 'excel_icon.png'
    pdf_icon = 'pdf_icon.png'
    file_extension = doc.attachment.url.split(".")[-1].downcase
    if file_extension.include?('pdf')
      return pdf_icon
    elsif file_extension.include?('doc')
      return word_icon
    else
      return excel_icon
    end
  end
  def get_doc_name(filename)
    return  (filename) ? filename.gsub(/[_]/, ' ') : ''
  end
end
end

app/views/spree/admin/docs/_form.html.erb
<div data-hook="admin_doc_form_fields">
  <div class="four columns alpha">
    <div data-hook="file" class="field">
      <%= f.label Spree.t(:filename) %><br>
      <%= f.file_field :attachment %>
    </div>
    <div data-hook="variant" class="field">
      <%= f.label Spree::Variant.model_name.human %><br>
      <%= f.select :viewable_id, @variants, {}, {:class => 'select2 fullwidth'} %>
    </div>
  </div>
  <div data-hook="alt_text" class="field omega five columns">
    <%= f.label Spree.t(:alt_text) %><br>
    <%= f.text_area :alt, :rows => 4, :class => 'fullwidth' %>
    <%= f.label :display_name %><br>
    <%= f.text_area :caption, :rows => 4, :class => 'fullwidth' %>
  </div>
</div>

<div class="clear"></div>

app/views/spree/admin/docs/edit.html.erb
<%= render :partial => 'spree/admin/shared/product_sub_menu' %>

<%= render :partial => 'spree/admin/shared/product_tabs', :locals => { :current => 'Docs' } %>

<%= render :partial => 'spree/shared/error_messages', :locals => { :target => @doc } %>

<% content_for :page_actions do %>
  <li><%= button_link_to Spree.t(:back_to_docs_list), admin_product_docs_url(@product), :icon => 'icon-arrow-left' %></li>
<% end %>

<%= form_for [:admin, @product, @doc], :html => { :multipart => true } do |f| %>
  <fieldset data-hook="edit_doc">
    <legend align="center"><%= @doc.attachment_file_name%></legend>
    <div data-hook="thumbnail" class="field alpha three columns align-center">
      <%= f.label :document %><br>
      <%= image_tag( get_doc_icon(@doc) ) %>
      <%= link_to(@doc.attachment.original_filename, @doc.attachment.url) %>
    </div>
    <div class="nine columns omega">
      <%= render :partial => 'form', :locals => { :f => f } %>  
    </div>
    <div class="clear"></div>
    <div class="form-buttons filter-actions actions" data-hook="buttons">
      <%= button Spree.t(:update), 'icon-refresh' %>
      <span class="or"><%= Spree.t(:or) %></span>
      <%= link_to Spree.t(:cancel), admin_product_docs_url(@product), :id => 'cancel_link', :class => 'button icon-remove' %>
    </div>
  </fieldset>
<% end %>

app/views/spree/admin/docs/index.html.erb
<% content_for :head do %>
  <script type="text/javascript">
    jQuery(document).ready(function(){  
      
      jQuery('#new_doc_link').click(function (event) { 
        event.preventDefault();
        // jQuery(this).hide();
        jQuery.ajax({type: 'GET', url: this.href, data: ({authenticity_token: AUTH_TOKEN}), success: function(r){ jQuery('#docs').html(r);} });
      });
      
    });
  </script>
<% end %>

<%= render :partial => 'spree/admin/shared/product_sub_menu' %>
<%= render :partial => 'spree/admin/shared/product_tabs', :locals => {:current => 'Docs'} %>

<% content_for :page_actions do %>
  <li><%= link_to_with_icon('icon-plus', Spree.t(:new_doc), new_admin_product_doc_url(@product), :id => 'new_doc_link', :class => 'button') %></li>
<% end %>

<div id="docs" data-hook></div>

<% unless @product.docs.any? || @product.variant_docs.any? %>
  <div class="no-objects-found">
    <%= Spree.t(:no_docs_found) %>.
  </div>
<% else %>
  <table class="index sortable" data-hook="docs_table" data-sortable-link="<%= update_positions_admin_product_docs_url(@product) %>">
    <colgroup>
      <col style="width: 5%">
      <col style="width: 10%">
      <% if @product.has_variants? %>
        <col style="width: 25%">
      <% end %>
      <col style="width: 45%">
      <col style="width: 15%">
    </colgroup>
    <thead>
      <tr data-hook="docs_header">
        <th colspan="2"><%= Spree.t(:doc_type) %></th>
        <% if @product.has_variants? %>
          <th><%= Spree.t(:display_name) %></th>
        <% end %>
        <th><%= Spree.t(:doc_name) %></th>
        <th class="actions"></th>
      </tr>
    </thead>

    <tbody>
      <% (@product.variant_docs).each do |doc| %>
        <tr id="<%= spree_dom_id doc %>" data-hook="docs_row" class="<%= cycle('odd', 'even')%>">
          <td class="no-border">
            <span class="handle"></span>
          </td>
          <td>
           <%= image_tag(get_doc_icon(doc), :align => 'left') %>
          </td>
          <% if @product.has_variants? %>
            <td><%= doc.caption %></td>
          <% end %>
          <td><%= link_to truncate(doc.attachment.original_filename, :length => 30), doc.attachment.url %></td>
          <td class="actions">
            <%= link_to_with_icon 'icon-edit', Spree.t(:edit), edit_admin_product_doc_url(@product, doc), :no_text => true, :data => {:action => 'edit'} %>
            <%= link_to_delete doc, { :url => admin_product_doc_url(@product, doc), :no_text => true } %>
          </td>
        </tr>
      <% end %>
    </tbody>
  </table>
<% end %>

app/views/spree/admin/docs/new.html.erb
<script type="text/javascript">    
  jQuery('#cancel_link').click(function (event) { 
    jQuery('#new_doc_link').show();
    jQuery('#docs').html('');
  });  
 
</script>
 
<%= form_for [:admin, @product, @doc], :html => { :multipart => true } do |f| %>
  <fieldset data-hook="new_doc">
    <legend align="center"><%= Spree.t(:new_doc) %></legend>

      <%= render :partial => 'form', :locals => { :f => f } %>
    
      <div class="form-buttons filter-actions actions" data-hook="buttons">
        <%= button Spree.t(:update), 'icon-refresh' %>
        <span class="or"><%= Spree.t(:or) %></span>
        <%= link_to_with_icon 'icon-remove', Spree.t(:cancel), admin_product_docs_url(@product), :id => 'cancel_link', :class => 'button' %>
      </div>
  </fieldset>
<% end %>

app/views/spree/admin/products/_docs.html.erb
<li<%== ' class="active"' if current == 'Documents' %>>
  <%= link_to_with_icon 'icon-file', "Documents",admin_product_docs_url(@product) %>
</li>

app/views/spree/products/_product_documents.html.erb
<% if @product and !@product.docs.empty? %>
  <div class="panel panel-default">
    <div class="panel-heading">
      <h4>
        <i class="fa fa-file"></i>
        <span id="product_downloads">
          <%= Spree.t(:product_downloads) %>
        </span>
      </h4>
    </div>
    <% if @product.docs.empty? %>
      <p><%= Spree.t("none") %></p>
    <% else %>
      <table class="table">
        <% @product.docs.each do |doc| %>
          <tr>
            <td>
              <i class="fa fa-angle-double-down"></i>
              <%= link_to(doc.attachment.instance.caption, doc.attachment.url, { :target => "_blank" }) %>
            </td>
          </tr>
        <% end %>
      </table>
    <% end %>
  </div>
<% end %>